$(document).ready(function(){
    $(".img1").click(function(){
        $(".one").css({
            display:"block"
        })
        $(".two").css({
            display:"none"
        })
        $(".three").css({
            display:"none"
        })
        $(".four").css({
            display:"none"
        })
    })
    $(".img2").click(function(){
        $(".one").css({
            display:"none"
        })
        $(".two").css({
            display:"block"
        })
        $(".three").css({
            display:"none"
        })
        $(".four").css({
            display:"none"
        })
    })
    $(".img3").click(function(){
        $(".one").css({
            display:"none"
        })
        $(".two").css({
            display:"none"
        })
        $(".three").css({
            display:"block"
        })
        $(".four").css({
            display:"none"
        })
    })
    $(".img4").click(function(){
        $(".one").css({
            display:"none"
        })
        $(".two").css({
            display:"none"
        })
        $(".three").css({
            display:"none"
        })
        $(".four").css({
            display:"block"
        })
    })
})